# Generated by Django 5.2.5 on 2026-09-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientuser_carried_demo_earnings_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='clientuser',
            constraint=models.CheckConstraint(condition=models.Q(('demo_progress__lte', 15)), name='demo_progress_at_most_15'),
        ),
        migrations.AddConstraint(
            model_name='clientuser',
            constraint=models.CheckConstraint(condition=models.Q(('client_progress__lte', 35)), name='client_progress_at_most_35'),
        ),
    ]
