# Generated by Django 5.2.5 on 2026-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clientuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='clientuser',
            name='demo_progress_at_most_15',
        ),
        migrations.RemoveConstraint(
            model_name='clientuser',
            name='client_progress_at_most_35',
        ),
        migrations.AddField(
            model_name='clientuser',
            name='assignment_status',
            field=models.CharField(choices=[('demo', 'Demo'), ('client', 'Client')], default='demo', max_length=10),
        ),
    ]
