# Generated by Django 5.2.5 on 2026-09-21 21:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClientUser',
            fields=[
            ],
            options={
                'verbose_name': 'Client User',
                'verbose_name_plural': 'Client Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.clientuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DemoUser',
            fields=[
            ],
            options={
                'verbose_name': 'Demo User',
                'verbose_name_plural': 'Demo Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.clientuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
