version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
