# Generated by Django 5.2.5 on 2026-09-20 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('demo', 'Demo'), ('client', 'Client')], max_length=10)),
                ('previous_progress', models.PositiveSmallIntegerField()),
                ('new_progress', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_changes_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssignmentLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('demo', 'Demo'), ('client', 'Client')], max_length=10)),
                ('lot_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('task_name', models.CharField(max_length=150)),
                ('task_description', models.TextField(blank=True)),
                ('task_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_earning', models.DecimalField(decimal_places=2, max_digits=12)),
                ('task_link', models.URLField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('assignment_type', 'lot_number'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'assignment_type', 'lot_number'), name='unique_employee_assignment_lot')],
            },
        ),
    ]
