# Generated by Django 5.2.5 on 2026-09-20 23:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def attach_existing_assignments(apps, schema_editor):
    TaskDefinition = apps.get_model('assignments', 'TaskDefinition')
    AssignmentLot = apps.get_model('assignments', 'AssignmentLot')
    definitions = {}
    for assignment in AssignmentLot.objects.order_by('assignment_type', 'lot_number', 'id'):
        key = (assignment.assignment_type, assignment.lot_number)
        task = definitions.get(key)
        if task is None:
            task, _ = TaskDefinition.objects.get_or_create(
                assignment_type=assignment.assignment_type,
                lot_number=assignment.lot_number,
                defaults={
                    'task_name': assignment.task_name,
                    'task_description': assignment.task_description,
                    'task_value': assignment.task_value,
                    'employee_earning': assignment.employee_earning,
                    'task_link': assignment.task_link,
                },
            )
            definitions[key] = task
        AssignmentLot.objects.filter(pk=assignment.pk).update(task_definition_id=task.pk)
    # Earlier versions provisioned Client lots before activation. Keep the current
    # assignment rule consistent for existing Demo users as well.
    AssignmentLot.objects.filter(employee__assignment_status='demo', assignment_type='client').delete()


def detach_existing_assignments(apps, schema_editor):
    AssignmentLot = apps.get_model('assignments', 'AssignmentLot')
    AssignmentLot.objects.update(task_definition_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('accounts', '0004_alter_clientuser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('demo', 'Demo'), ('client', 'Client')], max_length=10)),
                ('lot_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('task_name', models.CharField(max_length=150)),
                ('task_description', models.TextField(blank=True)),
                ('task_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_earning', models.DecimalField(decimal_places=2, max_digits=12)),
                ('task_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('assignment_type', 'lot_number'),
                'constraints': [models.UniqueConstraint(fields=('assignment_type', 'lot_number'), name='unique_assignment_type_lot_number')],
            },
        ),
        migrations.AddField(
            model_name='assignmentlot',
            name='task_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.taskdefinition'),
        ),
        migrations.RunPython(attach_existing_assignments, detach_existing_assignments),
        migrations.AddConstraint(
            model_name='assignmentlot',
            constraint=models.UniqueConstraint(fields=('employee', 'task_definition'), name='unique_employee_task_definition'),
        ),
    ]
